# Generated by Django 3.2 on 2022-03-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('image', models.ImageField(default='image', upload_to='about_us/')),
            ],
            options={
                'verbose_name': 'about us',
                'verbose_name_plural': 'about us',
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Chef/')),
            ],
            options={
                'verbose_name': 'chef',
                'verbose_name_plural': 'chef',
            },
        ),
        migrations.CreateModel(
            name='Why_Choose_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name': 'why choose us',
                'verbose_name_plural': 'why choose us',
            },
        ),
    ]
